server:
  port : ${SERVER_PORT:8080}
spring:
  application:
    name: publicService
feign:
  #circuitbreaker:
  #  enabled: true
  client:
    subscriptions:
      name: subscriptions
      url: ${SPRING_CLOUD_GATEWAY_URL:http://localhost:8080}/subscriptionservice/api
    config:
      default:
        loggerLevel: ${FEIGN_LOG_LEVEL:basic}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: ${HOSTNAME:localhost}
